//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _wp_point.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int RequestChunkSize {
            get {
                return ((int)(this["RequestChunkSize"]));
            }
            set {
                this["RequestChunkSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SSLVerify {
            get {
                return ((bool)(this["SSLVerify"]));
            }
            set {
                this["SSLVerify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mng-dev-waitingpass.webimpact.co.jp/api/pointcard/member/set")]
        public string APIMemberImportURL {
            get {
                return ((string)(this["APIMemberImportURL"]));
            }
            set {
                this["APIMemberImportURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mng-dev-waitingpass.webimpact.co.jp/api/pointcard/member/get")]
        public string APIMemberExportURL {
            get {
                return ((string)(this["APIMemberExportURL"]));
            }
            set {
                this["APIMemberExportURL"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=POINTCARD;User ID=sa;Password=12345678")]
        public string POINTCARDConnString {
            get {
                return ((string)(this["POINTCARDConnString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9013:OA推進センター,9021:金沢まいもん寿司")]
        public string PrinterCorpCode {
            get {
                return ((string)(this["PrinterCorpCode"]));
            }
            set {
                this["PrinterCorpCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0001:吹田グリーンプレイス店")]
        public string PrinterTempoCode {
            get {
                return ((string)(this["PrinterTempoCode"]));
            }
            set {
                this["PrinterTempoCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mng-dev-waitingpass.webimpact.co.jp/api/pointcard/member/auth")]
        public string APIAuthQRCodeURL {
            get {
                return ((string)(this["APIAuthQRCodeURL"]));
            }
            set {
                this["APIAuthQRCodeURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mng-dev-waitingpass.webimpact.co.jp/api/pointcard/member/search")]
        public string APICheckEmailURL {
            get {
                return ((string)(this["APICheckEmailURL"]));
            }
            set {
                this["APICheckEmailURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WpPointCardBackUp_Path {
            get {
                return ((string)(this["WpPointCardBackUp_Path"]));
            }
            set {
                this["WpPointCardBackUp_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.waitingpass.com/heishirou/member/api/zip")]
        public string APIAddressSearchURL {
            get {
                return ((string)(this["APIAddressSearchURL"]));
            }
            set {
                this["APIAddressSearchURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\GitProject\\maimon-suita\\program\\wp_point\\WP_PCARDIF\\bin\\Debug\\WP_PCARDIF.exe")]
        public string WP_PCARDIF_Path {
            get {
                return ((string)(this["WP_PCARDIF_Path"]));
            }
            set {
                this["WP_PCARDIF_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\GitProject\\maimon-suita\\program\\wp_point\\wp_upload_point\\bin\\Debug\\wp_upload_p" +
            "oint.exe")]
        public string WP_UPLOAD_POINT_Path {
            get {
                return ((string)(this["WP_UPLOAD_POINT_Path"]));
            }
            set {
                this["WP_UPLOAD_POINT_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\WPPointCard\\Data\\CSV移動元フォルダ")]
        public string PointCardMemoryDataFilePath {
            get {
                return ((string)(this["PointCardMemoryDataFilePath"]));
            }
            set {
                this["PointCardMemoryDataFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("901300101")]
        public string PointCardMemoryDataFileName {
            get {
                return ((string)(this["PointCardMemoryDataFileName"]));
            }
            set {
                this["PointCardMemoryDataFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XBJUJOH")]
        public string QRCodeFixedString {
            get {
                return ((string)(this["QRCodeFixedString"]));
            }
            set {
                this["QRCodeFixedString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mng-dev-waitingpass.webimpact.co.jp/api/pointcard/member/merge")]
        public string APIMemberMergeURL {
            get {
                return ((string)(this["APIMemberMergeURL"]));
            }
            set {
                this["APIMemberMergeURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mng-dev-waitingpass.webimpact.co.jp/api/pointcard/shop/auth")]
        public string APIAuthShopURL {
            get {
                return ((string)(this["APIAuthShopURL"]));
            }
            set {
                this["APIAuthShopURL"] = value;
            }
        }
    }
}
